### ISSUE TITLE
It uses __dirname in eval and similar things, and can't be bundled correctly. Hence we are adding it to the list of external packages.

### ISSUE THREAD

**Issue by albrtkinn** [PingIsFun/HitBoxPlus#10]
It uses __dirname in eval and similar things, and can't be bundled correctly. Hence we are adding it to the list of external packages.

## Bug

- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Errors have a helpful link attached, see `contributing.md`

## Feature

- [ ] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
- [ ] Related issues linked using `fixes #number`
- [ ] Integration tests added
- [ ] Documentation added
- [ ] Telemetry added. In case of a feature if it's used or not.
- [ ] Errors have a helpful link attached, see `contributing.md`

## Documentation / Examples

- [ ] Make sure the linting passes by running `pnpm build && pnpm lint`
- [ ] The "examples guidelines" are followed from [our contributing doc](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

__Originally posted by @shuding in https://github.com/vercel/next.js/pull/42323__

**Comment by PingIsFun** [comment]
U sure this is the right repo?
