### ISSUE TITLE
Colth config API version message 1.18.2

### ISSUE THREAD

**Issue by Nukecraft5419** [PingIsFun/HitBoxPlus#18]
- Mod 'HitBox+' (hitboxplus) 0.2.2 recommends any version between 6.4 (inclusive) and 6.5- (exclusive) of mod 'Cloth Config v6' (cloth-config), but only the wrong version is present: 6.3.81!
	 - You should install any version between 6.4 (inclusive) and 6.5- (exclusive) of mod 'Cloth Config v6' (cloth-config) for the optimal experience.

**Comment by PingIsFun** [comment]
can you send the full log

**Comment by Nukecraft5419** [comment]
https://paste.ee/p/WxEmn

**Comment by PingIsFun** [comment]
Did your game crash?

**Comment by Nukecraft5419** [comment]
No, but it keeps advising me to install a version of Colth Config API

**Comment by PingIsFun** [comment]
if it works just ignore

**Comment by PingIsFun** [comment]
ill try to get a fix soon™️
