### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Julienraptor01** [PingIsFun/HitBoxPlus#2]
Add a setting to make all players ennemies by default
Add a thing and a setting so middle click elevate the trust in someone
Ex : middle click on ennemy for neutral then again for friend
Add a thing and a setting so middle click while crouching reduce the trust in someone
Ex : previous but reversed
Add a settings to allow to cycle trough trust level
Ex : in 1st example go back to ennemy after friend
Add a way to inverse the crouching behavior
Ex : by default crouch lower and non-crouch elevate but if this setting is enable it's the opposite behavior

Q: Why make everything settings ?
R: Because maybe someone won't like the feature and want it disabled

**Comment by PingIsFun** [comment]
What do you mean by  
> (why make settings ? because some might not like one utility)
Make the setting togglable?

**Comment by Julienraptor01** [comment]
I'm just auto asking the question of why I want everything togglable
Just in case someone want to ask the question, they already have the answer

**Comment by Julienraptor01** [comment]
I'm just auto asking the question of why I want everything togglable
Just in case someone want to ask the question, they already have the answer

Btw i already used your mod and it's so nice

**Comment by Julienraptor01** [comment]
And i have another idea but i may be harder
The idea is being able to disable some hitbox :
By example disabling falling blocks or item frames/paintings

**Comment by PingIsFun** [comment]
> Add a setting to make all players ennemies by default
Add a thing and a setting so middle click elevate the trust in someone
Ex : middle click on ennemy for neutral then again for friend
Add a thing and a setting so middle click while crouching reduce the trust in someone
Ex : previous but reversed
Add a settings to allow to cycle trough trust level
Ex : in 1st example go back to ennemy after friend
Add a way to inverse the crouching behavior
Ex : by default crouch lower and non-crouch elevate but if this setting is enable it's the opposite behavior

In response to this i think this is a bit too complicated.
I will just probably add a command like `/hitboxplus add enemy [name]` and the same for friend
or middle clicking only having one functionality

**Comment by Julienraptor01** [comment]
> > I'm just auto asking the question of why I want everything togglable
> Just in case someone want to ask the question, they already have the answer
> 
> So if i understand this correctly you are asking why are there so many options?
> Short answer i want customization if you don't want to deal with all the options just leave them disabled and change the general options.  

no it's the opposite lol i ask for many option and i take the pov of someone else who could think why does this person ask for so many options

**Comment by Julienraptor01** [comment]
> > Add a setting to make all players ennemies by default
> Add a thing and a setting so middle click elevate the trust in someone
> Ex : middle click on ennemy for neutral then again for friend
> Add a thing and a setting so middle click while crouching reduce the trust in someone
> Ex : previous but reversed
> Add a settings to allow to cycle trough trust level
> Ex : in 1st example go back to ennemy after friend
> Add a way to inverse the crouching behavior
> Ex : by default crouch lower and non-crouch elevate but if this setting is enable it's the opposite behavior
> 
> In response to this i think this is a bit too complicated.
> I will just probably add a command like `/hitboxplus add enemy [name]` and the same for friend
> or middle clicking only having one functionality 
> 

Ok

**Comment by PingIsFun** [comment]
Ok so i've decided how i'll implement this. 

You will have a middleClick setting with 4 options

- disabled
- toggle friend 
- toggle enemy
- cycle

And maybe i'll add commands for 
- /hitboxplus add/remove/list friend/enemy name
- only doing /hitboxplus list will list both friends and enemies 

Also ty for all the feedback.

**Comment by PingIsFun** [comment]
Added middle clicking functionality for the commands all further discussion will be in #15 if you have any other ideas open another issue.
